// <auto-generated />
using System;
using System.Collections.Generic;
using Apex.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apex.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820221155_AddPasswordResetToken")]
    partial class AddPasswordResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apex.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PointValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TickValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InstrumentId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Currency = "USD",
                            InstrumentName = "E-mini S&P 500",
                            PointValue = 50m,
                            Symbol = "ES",
                            TickSize = 0.25m,
                            TickValue = 12.50m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Currency = "USD",
                            InstrumentName = "Micro E-mini S&P 500",
                            PointValue = 5m,
                            Symbol = "MES",
                            TickSize = 0.25m,
                            TickValue = 1.25m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Currency = "USD",
                            InstrumentName = "E-mini Nasdaq-100",
                            PointValue = 20m,
                            Symbol = "NQ",
                            TickSize = 0.25m,
                            TickValue = 5.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Currency = "USD",
                            InstrumentName = "Micro E-mini Nasdaq-100",
                            PointValue = 2m,
                            Symbol = "MNQ",
                            TickSize = 0.25m,
                            TickValue = 0.50m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Currency = "USD",
                            InstrumentName = "E-mini Dow ($5)",
                            PointValue = 5m,
                            Symbol = "YM",
                            TickSize = 1m,
                            TickValue = 5.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Currency = "USD",
                            InstrumentName = "Micro E-mini Dow",
                            PointValue = 0.50m,
                            Symbol = "MYM",
                            TickSize = 1m,
                            TickValue = 0.50m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Currency = "USD",
                            InstrumentName = "E-mini Russell 2000",
                            PointValue = 50m,
                            Symbol = "RTY",
                            TickSize = 0.10m,
                            TickValue = 5.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Currency = "USD",
                            InstrumentName = "Micro E-mini Russell 2000",
                            PointValue = 5m,
                            Symbol = "M2K",
                            TickSize = 0.10m,
                            TickValue = 0.50m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Currency = "USD",
                            InstrumentName = "Gold",
                            PointValue = 100m,
                            Symbol = "GC",
                            TickSize = 0.10m,
                            TickValue = 10.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Currency = "USD",
                            InstrumentName = "Micro Gold",
                            PointValue = 10m,
                            Symbol = "MGC",
                            TickSize = 0.10m,
                            TickValue = 1.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000011"),
                            Currency = "USD",
                            InstrumentName = "Crude Oil",
                            PointValue = 1000m,
                            Symbol = "CL",
                            TickSize = 0.01m,
                            TickValue = 10.00m,
                            Type = "Future"
                        },
                        new
                        {
                            InstrumentId = new Guid("a1000000-0000-0000-0000-000000000012"),
                            Currency = "USD",
                            InstrumentName = "Micro Crude Oil",
                            PointValue = 100m,
                            Symbol = "MCL",
                            TickSize = 0.01m,
                            TickValue = 1.00m,
                            Type = "Future"
                        });
                });

            modelBuilder.Entity("Apex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Apex.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Apex.Domain.Entities.StrategyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategyRules");
                });

            modelBuilder.Entity("Apex.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmotionalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HTFBias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mistakes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RiskReward")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.PrimitiveCollection<List<string>>("Screenshots")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("TakeProfit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Apex.Domain.Entities.TradeExit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Contracts")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeExits");
                });

            modelBuilder.Entity("Apex.Domain.Entities.TradeRuleCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrategyRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyRuleId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeRuleChecks");
                });

            modelBuilder.Entity("Apex.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StrategyInstruments", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.HasKey("InstrumentId", "StrategyId");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategyInstruments");
                });

            modelBuilder.Entity("Apex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Apex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apex.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("Apex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apex.Domain.Entities.StrategyRule", b =>
                {
                    b.HasOne("Apex.Domain.Entities.Strategy", "Strategy")
                        .WithMany("Rules")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Apex.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Apex.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Apex.Domain.Entities.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apex.Domain.Entities.TradeExit", b =>
                {
                    b.HasOne("Apex.Domain.Entities.Trade", "Trade")
                        .WithMany("Exits")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Apex.Domain.Entities.TradeRuleCheck", b =>
                {
                    b.HasOne("Apex.Domain.Entities.StrategyRule", "StrategyRule")
                        .WithMany()
                        .HasForeignKey("StrategyRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Domain.Entities.Trade", "Trade")
                        .WithMany("RuleChecks")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyRule");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("StrategyInstruments", b =>
                {
                    b.HasOne("Apex.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Domain.Entities.Strategy", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Apex.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Exits");

                    b.Navigation("RuleChecks");
                });

            modelBuilder.Entity("Apex.Domain.Entities.User", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
